#!/bin/sh
#nitrogen --restore &
#$HOME/my\ scripts/xrandr-newmode.sh 1920 1080  60  &
#killall spacefm
#killall wbar
#killall fbpanel 
#xgamma -rgamma 1.3 -bgamma .9 -ggamma 1.3  &
exec xpad & 
#exec fbpanel   & 

sleep 1; sudo nm-applet  &
sudo opensnitch-ui &
~/.config/openbox/scripts/refresh.sh 

#exec spacefm --desktop & 
 udisksctl  mount  -o nosuid,noatime,nodev,rw  -b /dev/sdb3 
#sleep 2; exec  wbar &  

